// Seed sample data: categories, products, test users (with loyalty points), a discount code.
// Run with: npx prisma db seed
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Real product photos downloaded from each brand's official catalog/site
// (see scripts/_download-brand-images.mjs for sources); served from /public/uploads/brands.
function brandImg(file) {
  return `/uploads/brands/${file}`;
}

async function main() {
  await prisma.loyaltySettings.upsert({
    where: { id: "default" },
    create: { id: "default" },
    update: {},
  });

  const categories = await Promise.all(
    [
      { name: "کاشی دیوار", slug: "wall-tile", description: "انواع کاشی دیوار برای آشپزخانه، حمام و نما" },
      { name: "کاشی کف", slug: "floor-tile", description: "کاشی مقاوم و ضدلغزش برای کف اماکن مسکونی و تجاری" },
      { name: "سرامیک", slug: "ceramic", description: "سرامیک‌های باکیفیت با طرح‌های متنوع" },
      { name: "پرسلان", slug: "porcelain", description: "پرسلان‌های مقاوم با جذب آب پایین" },
    ].map((c) => prisma.category.upsert({ where: { slug: c.slug }, create: c, update: c }))
  );

  const [wall, floor, ceramic, porcelain] = categories;

  const products = [
    {
      name: "کاشی دیوار الوند طرح مرمر سفید ۳۰×۶۰",
      slug: "wall-tile-white-marble-30x60",
      description: "کاشی دیوار الوند با طرح مرمر سفید، مناسب آشپزخانه و حمام، سطح براق و درخشان.",
      nameEn: "Alvand Wall Tile – White Marble 30×60",
      nameAz: "Alvand divar kafeli – Ağ mərmər 30×60",
      nameKa: "ალვანდის კედლის ფილა – თეთრი მარმარილო 30×60",
      descriptionEn: "Alvand wall tile with a white marble pattern, glossy finish, ideal for kitchens and bathrooms.",
      descriptionAz: "Ağ mərmər naxışlı Alvand divar kafeli, parlaq səth, mətbəx və hamam üçün uyğundur.",
      descriptionKa: "ალვანდის კედლის ფილა თეთრი მარმარილოს ნიმუშით, პრიალა ზედაპირი, შესაფერისია სამზარეულოსა და აბაზანისთვის.",
      categoryId: wall.id,
      brand: "الوند",
      size: "30x60",
      color: "سفید",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 380000,
      unit: "SQUARE_METER",
      stock: 240,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-1.jpg")],
    },
    {
      name: "کاشی دیوار نیلو طرح چوب بژ ۲۵×۴۰",
      slug: "wall-tile-beige-wood-25x40",
      description: "کاشی دیوار نیلو با طراحی الهام‌گرفته از چوب طبیعی، رنگ بژ گرم، مناسب فضای نشیمن.",
      nameEn: "Nilou Wall Tile – Beige Wood 25×40",
      nameAz: "Nilu divar kafeli – Bej ağac 25×40",
      nameKa: "ნილუს კედლის ფილა – ბეჟი ხის ნიმუში 25×40",
      descriptionEn: "Nilou wall tile inspired by natural wood, warm beige tone, well suited to living rooms.",
      descriptionAz: "Təbii ağacdan ilhamlanan Nilu divar kafeli, isti bej rəng, oturma otağı üçün uyğundur.",
      descriptionKa: "ნილუს კედლის ფილა ბუნებრივი ხისგან შთაგონებული, თბილი ბეჟი ტონი, შესაფერისია მისაღები ოთახისთვის.",
      categoryId: wall.id,
      brand: "نیلو",
      size: "25x40",
      color: "بژ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 295000,
      unit: "SQUARE_METER",
      stock: 180,
      isFeatured: false,
      isNew: true,
      images: [brandImg("nilou-2.jpg")],
    },
    {
      name: "کاشی کف الوند طرح گرانیت طوسی ۶۰×۶۰",
      slug: "floor-tile-gray-granite-60x60",
      description: "کاشی کف الوند با طرح گرانیت طوسی، مقاوم در برابر سایش، مناسب راهرو و پذیرایی.",
      nameEn: "Alvand Floor Tile – Gray Granite 60×60",
      nameAz: "Alvand döşəmə kafeli – Boz qranit 60×60",
      nameKa: "ალვანდის იატაკის ფილა – ნაცრისფერი გრანიტი 60×60",
      descriptionEn: "Alvand floor tile with a gray granite pattern, wear-resistant, ideal for hallways and living rooms.",
      descriptionAz: "Boz qranit naxışlı Alvand döşəmə kafeli, aşınmaya davamlı, dəhliz və qonaq otağı üçün uyğundur.",
      descriptionKa: "ალვანდის იატაკის ფილა ნაცრისფერი გრანიტის ნიმუშით, ცვეთამედეგი, შესაფერისია დერეფნისა და მისაღები ოთახისთვის.",
      categoryId: floor.id,
      brand: "الوند",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 520000,
      unit: "SQUARE_METER",
      stock: 150,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-2.jpg")],
    },
    {
      name: "کاشی کف مرجان ضدلغزش طرح سنگ تیره ۴۰×۴۰",
      slug: "floor-tile-dark-stone-antislip-40x40",
      description: "کاشی کف مرجان ضدلغزش با طرح سنگ طبیعی تیره، مناسب حیاط، تراس و پارکینگ.",
      nameEn: "Marjan Anti-Slip Floor Tile – Dark Stone 40×40",
      nameAz: "Mərcan sürüşməyə qarşı döşəmə kafeli – Tünd daş 40×40",
      nameKa: "მარჯანის სრიალსაწინააღმდეგო იატაკის ფილა – მუქი ქვა 40×40",
      descriptionEn: "Marjan anti-slip floor tile with a dark natural stone pattern, suited to yards, terraces, and parking areas.",
      descriptionAz: "Mərcan sürüşməyə qarşı döşəmə kafeli, tünd təbii daş naxışı, həyət, terras və avtodayanacaq üçün uyğundur.",
      descriptionKa: "მარჯანის სრიალსაწინააღმდეგო იატაკის ფილა მუქი ბუნებრივი ქვის ნიმუშით, შესაფერისია ეზოს, ტერასისა და პარკინგისთვის.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "40x40",
      color: "طوسی تیره",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 410000,
      unit: "SQUARE_METER",
      stock: 200,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-1.jpg")],
    },
    {
      name: "سرامیک نیلو طرح گل سنتی ۲۰×۲۰",
      slug: "ceramic-traditional-flower-20x20",
      description: "سرامیک نیلو با طرح سنتی گل، مناسب دکوراسیون ایرانی و سنتی.",
      nameEn: "Nilou Ceramic – Traditional Flower 20×20",
      nameAz: "Nilu keramika – Ənənəvi gül 20×20",
      nameKa: "ნილუს კერამიკა – ტრადიციული ყვავილი 20×20",
      descriptionEn: "Nilou ceramic with a traditional floral pattern, well suited to Persian and classic decor.",
      descriptionAz: "Ənənəvi gül naxışlı Nilu keramika, İran və klassik dekor üçün uyğundur.",
      descriptionKa: "ნილუს კერამიკა ტრადიციული ყვავილის ნიმუშით, შესაფერისია სპარსული და კლასიკური დეკორისთვის.",
      categoryId: ceramic.id,
      brand: "نیلو",
      size: "20x20",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 260000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-3.jpg")],
    },
    {
      name: "سرامیک کف پرسپولیس آشپزخانه طرح هگزاگونال",
      slug: "ceramic-hexagon-kitchen-floor",
      description: "سرامیک کف پرسپولیس با طرح شش‌ضلعی مدرن، مناسب آشپزخانه‌های امروزی.",
      nameEn: "Persepolis Kitchen Floor Ceramic – Hexagon",
      nameAz: "Persepolis mətbəx döşəməsi üçün keramika – Heksaqonal",
      nameKa: "ფერსეპოლისის სამზარეულოს იატაკის კერამიკა – ჰექსაგონი",
      descriptionEn: "Persepolis kitchen floor ceramic with a modern hexagon pattern, suited to contemporary kitchens.",
      descriptionAz: "Persepolis mətbəx döşəmə keramikası, müasir heksaqonal naxış, müasir mətbəxlər üçün uyğundur.",
      descriptionKa: "ფერსეპოლისის სამზარეულოს იატაკის კერამიკა თანამედროვე ჰექსაგონის ნიმუშით, შესაფერისია თანამედროვე სამზარეულოებისთვის.",
      categoryId: ceramic.id,
      brand: "پرسپولیس",
      size: "20x23",
      color: "سفید و مشکی",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 340000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: true,
      isNew: true,
      images: [brandImg("persepolis-1.jpg")],
    },
    {
      name: "پرسلان الوند مات طرح سیمانی ۸۰×۸۰",
      slug: "porcelain-matte-cement-80x80",
      description: "پرسلان الوند مات با طرح سیمانی مدرن، جذب آب بسیار پایین، مناسب فضاهای صنعتی و مدرن.",
      nameEn: "Alvand Matte Porcelain – Cement 80×80",
      nameAz: "Alvand mat farfor – Sement 80×80",
      nameKa: "ალვანდის მქრქალი ფაიფური – ცემენტი 80×80",
      descriptionEn: "Alvand matte porcelain with a modern cement pattern, very low water absorption, suited to industrial and modern spaces.",
      descriptionAz: "Alvand mat farfor, müasir sement naxışı, çox aşağı su hopdurma, sənaye və müasir məkanlar üçün uyğundur.",
      descriptionKa: "ალვანდის მქრქალი ფაიფური თანამედროვე ცემენტის ნიმუშით, ძალიან დაბალი წყალშთანთქმა, შესაფერისია სამრეწველო და თანამედროვე სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "الوند",
      size: "80x80",
      color: "خاکستری روشن",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 690000,
      unit: "SQUARE_METER",
      stock: 75,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-3.jpg")],
    },
    {
      name: "پرسلان تبریز براق طرح مرمر طلایی ۶۰×۱۲۰",
      slug: "porcelain-gold-marble-60x120",
      description: "پرسلان بزرگ‌ابعاد تبریز با طرح مرمر طلایی، مناسب لابی و فضاهای لوکس.",
      nameEn: "Tabriz Glossy Porcelain – Gold Marble 60×120",
      nameAz: "Təbriz parlaq farfor – Qızılı mərmər 60×120",
      nameKa: "თბრიზის პრიალა ფაიფური – ოქროს მარმარილო 60×120",
      descriptionEn: "Large-format Tabriz porcelain with a gold marble pattern, suited to lobbies and luxury spaces.",
      descriptionAz: "Böyük ölçülü Təbriz farfor, qızılı mərmər naxışı, lobbi və lüks məkanlar üçün uyğundur.",
      descriptionKa: "მსხვილფორმატიანი თბრიზის ფაიფური ოქროს მარმარილოს ნიმუშით, შესაფერისია ლობისა და ლუქს სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "تبریز",
      size: "60x120",
      color: "کرم طلایی",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 890000,
      unit: "SQUARE_METER",
      stock: 40,
      isFeatured: false,
      isNew: true,
      images: [brandImg("tabriz-1.jpg")],
    },
    // --- برند تبریز ---
    {
      name: "کاشی دیوار تبریز طرح آباژور کرم ۲۵×۴۰",
      slug: "tabriz-wall-cream-abazhur-25x40",
      description: "کاشی دیوار تبریز با طرح آباژور کرم‌رنگ، یکی از پرفروش‌ترین طرح‌های صادراتی به بازار قفقاز.",
      nameEn: "Tabriz Wall Tile – Abazhur Cream 25×40",
      nameAz: "Təbriz divar kafeli – Abajur krem 25×40",
      nameKa: "თბრიზის კედლის ფილა – აბაჟური კრემისფერი 25×40",
      descriptionEn: "Tabriz wall tile with the cream Abazhur pattern, one of the brand's best-selling designs exported to the Caucasus market.",
      descriptionAz: "Təbriz divar kafeli, krem rəngli Abajur naxışı, Qafqaz bazarına ixrac olunan ən çox satılan naxışlardan biri.",
      descriptionKa: "თბრიზის კედლის ფილა კრემისფერი აბაჟურის ნიმუშით, ბრენდის ერთ-ერთი ყველაზე გაყიდვადი საექსპორტო დიზაინი კავკასიის ბაზრისთვის.",
      categoryId: wall.id,
      brand: "تبریز",
      size: "25x40",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 310000,
      unit: "SQUARE_METER",
      stock: 160,
      isFeatured: true,
      isNew: false,
      images: [brandImg("tabriz-2.jpg")],
    },
    {
      name: "کاشی کف تبریز پرسلان طوسی ۶۰×۶۰",
      slug: "tabriz-floor-gray-porcelain-60x60",
      description: "کاشی کف تبریز، پرسلان طوسی با دوام بالا، از محصولات صادراتی معتبر این برند.",
      nameEn: "Tabriz Floor Tile – Gray Porcelain 60×60",
      nameAz: "Təbriz döşəmə kafeli – Boz farfor 60×60",
      nameKa: "თბრიზის იატაკის ფილა – ნაცრისფერი ფაიფური 60×60",
      descriptionEn: "Tabriz floor tile, durable gray porcelain, one of the brand's reputable export products.",
      descriptionAz: "Təbriz döşəmə kafeli, davamlı boz farfor, brendin nüfuzlu ixrac məhsullarından biri.",
      descriptionKa: "თბრიზის იატაკის ფილა, გამძლე ნაცრისფერი ფაიფური, ბრენდის ერთ-ერთი სანდო საექსპორტო პროდუქტი.",
      categoryId: floor.id,
      brand: "تبریز",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("tabriz-3.jpg")],
    },
    // --- برند مرجان ---
    {
      name: "سرامیک مرجان بدنه قرمز ضداسید ۲۰×۲۰",
      slug: "marjan-red-body-acid-resistant-20x20",
      description: "سرامیک مرجان با بدنه قرمز لعاب‌دار و مقاوم در برابر اسید، مناسب پارکینگ و فضاهای تجاری.",
      nameEn: "Marjan Ceramic – Red Body, Acid-Resistant 20×20",
      nameAz: "Mərcan keramika – Qırmızı gövdə, turşuya davamlı 20×20",
      nameKa: "მარჯანის კერამიკა – წითელი ტანი, მჟავმედეგი 20×20",
      descriptionEn: "Marjan ceramic with a glazed red body, acid-resistant, suited to parking areas and commercial spaces.",
      descriptionAz: "Mərcan keramika, şirli qırmızı gövdə, turşuya davamlı, avtodayanacaq və kommersiya məkanları üçün uyğundur.",
      descriptionKa: "მარჯანის კერამიკა მოჭიქული წითელი ტანით, მჟავმედეგი, შესაფერისია პარკინგისა და კომერციული სივრცეებისთვის.",
      categoryId: ceramic.id,
      brand: "مرجان",
      size: "20x20",
      color: "قرمز",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 230000,
      unit: "SQUARE_METER",
      stock: 220,
      isFeatured: false,
      isNew: false,
      images: [brandImg("marjan-2.jpg")],
    },
    {
      name: "کاشی کف مرجان طرح گرانیت مشکی ۴۰×۴۰",
      slug: "marjan-black-granite-40x40",
      description: "کاشی کف مرجان با طرح گرانیت مشکی، از محصولات پرفروش این برند برای فضاهای مدرن.",
      nameEn: "Marjan Floor Tile – Black Granite 40×40",
      nameAz: "Mərcan döşəmə kafeli – Qara qranit 40×40",
      nameKa: "მარჯანის იატაკის ფილა – შავი გრანიტი 40×40",
      descriptionEn: "Marjan floor tile with a black granite pattern, one of the brand's best sellers for modern spaces.",
      descriptionAz: "Mərcan döşəmə kafeli, qara qranit naxışı, müasir məkanlar üçün brendin ən çox satılan məhsullarından biri.",
      descriptionKa: "მარჯანის იატაკის ფილა შავი გრანიტის ნიმუშით, ბრენდის ერთ-ერთი ყველაზე გაყიდვადი პროდუქტი თანამედროვე სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "40x40",
      color: "مشکی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 350000,
      unit: "SQUARE_METER",
      stock: 110,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-3.jpg")],
    },
    // --- برند پرسپولیس ---
    {
      name: "کاشی دیوار پرسپولیس طرح گلبرگ فانتزی ۲۵×۴۰",
      slug: "persepolis-flower-fantasy-25x40",
      description: "کاشی دیوار پرسپولیس با طرح فانتزی گلبرگ، مناسب دکوراسیون مدرن آشپزخانه.",
      nameEn: "Persepolis Wall Tile – Fantasy Petal 25×40",
      nameAz: "Persepolis divar kafeli – Fantastik ləçək 25×40",
      nameKa: "ფერსეპოლისის კედლის ფილა – ფანტასტიკური ფურცელი 25×40",
      descriptionEn: "Persepolis wall tile with a fantasy petal pattern, suited to modern kitchen decor.",
      descriptionAz: "Persepolis divar kafeli, fantastik ləçək naxışı, müasir mətbəx dekoru üçün uyğundur.",
      descriptionKa: "ფერსეპოლისის კედლის ფილა ფანტასტიკური ფურცლის ნიმუშით, შესაფერისია თანამედროვე სამზარეულოს დეკორისთვის.",
      categoryId: wall.id,
      brand: "پرسپولیس",
      size: "25x40",
      color: "صورتی روشن",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 275000,
      unit: "SQUARE_METER",
      stock: 170,
      isFeatured: false,
      isNew: true,
      images: [brandImg("persepolis-2.jpg")],
    },
    {
      name: "کاشی کف پرسپولیس طرح چوب روشن ۲۰×۱۲۰",
      slug: "persepolis-light-wood-20x120",
      description: "کاشی کف پرسپولیس با طرح چوب روشن کشیده، جایگزین اقتصادی پارکت برای کف منزل.",
      nameEn: "Persepolis Floor Tile – Light Wood 20×120",
      nameAz: "Persepolis döşəmə kafeli – Açıq ağac 20×120",
      nameKa: "ფერსეპოლისის იატაკის ფილა – ღია ხის ნიმუში 20×120",
      descriptionEn: "Persepolis floor tile with an elongated light wood pattern, an economical alternative to parquet flooring.",
      descriptionAz: "Persepolis döşəmə kafeli, uzunsov açıq ağac naxışı, parket üçün iqtisadi alternativ.",
      descriptionKa: "ფერსეპოლისის იატაკის ფილა წაგრძელებული ღია ხის ნიმუშით, პარკეტის ეკონომიური ალტერნატივა.",
      categoryId: floor.id,
      brand: "پرسپولیس",
      size: "20x120",
      color: "قهوه‌ای روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: false,
      price: 520000,
      unit: "SQUARE_METER",
      stock: 95,
      isFeatured: true,
      isNew: false,
      images: [brandImg("persepolis-3.jpg")],
    },
    // --- برند نیلو ---
    {
      name: "کاشی کف نیلو پرسلان روشن ۶۰×۶۰",
      slug: "nilou-light-porcelain-60x60",
      description: "کاشی کف نیلو، پرسلان روشن با کیفیت صادراتی، از پرفروش‌ترین سایزهای این برند.",
      nameEn: "Nilou Floor Tile – Light Porcelain 60×60",
      nameAz: "Nilu döşəmə kafeli – Açıq farfor 60×60",
      nameKa: "ნილუს იატაკის ფილა – ღია ფაიფური 60×60",
      descriptionEn: "Nilou floor tile, light-toned export-quality porcelain, one of the brand's best-selling sizes.",
      descriptionAz: "Nilu döşəmə kafeli, açıq tonlu ixrac keyfiyyətli farfor, brendin ən çox satılan ölçülərindən biri.",
      descriptionKa: "ნილუს იატაკის ფილა, ღია ტონის საექსპორტო ხარისხის ფაიფური, ბრენდის ერთ-ერთი ყველაზე გაყიდვადი ზომა.",
      categoryId: floor.id,
      brand: "نیلو",
      size: "60x60",
      color: "بژ روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 510000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-1.jpg")],
    },

    // --- برند سینا ---
    {
      name: "کاشی دیوار سینا طرح مدرن کرم ۲۵×۴۰",
      slug: "sina-wall-cream-modern-25x40",
      description: "کاشی دیوار سینا با طرح مدرن کرم‌رنگ، مناسب آشپزخانه و فضاهای نشیمن امروزی.",
      nameEn: "Sina Wall Tile – Modern Cream 25×40",
      nameAz: "Sina divar kafeli – Müasir krem 25×40",
      nameKa: "სინას კედლის ფილა – თანამედროვე კრემისფერი 25×40",
      descriptionEn: "Sina wall tile with a modern cream pattern, suited to kitchens and today's living spaces.",
      descriptionAz: "Sina divar kafeli, müasir krem naxışı, mətbəx və müasir oturma sahələri üçün uyğundur.",
      descriptionKa: "სინას კედლის ფილა თანამედროვე კრემისფერი ნიმუშით, შესაფერისია სამზარეულოსა და თანამედროვე საცხოვრებელი სივრცეებისთვის.",
      categoryId: wall.id,
      brand: "سینا",
      size: "25x40",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 300000,
      unit: "SQUARE_METER",
      stock: 190,
      isFeatured: true,
      isNew: false,
      images: [brandImg("sina-1.jpg"), brandImg("sina-3.jpg")],
    },
    {
      name: "کاشی کف سینا پرسلان طوسی ۶۰×۶۰",
      slug: "sina-floor-gray-porcelain-60x60",
      description: "کاشی کف سینا، پرسلان طوسی مقاوم در برابر سایش، مناسب راهرو و فضاهای پرتردد.",
      nameEn: "Sina Floor Tile – Gray Porcelain 60×60",
      nameAz: "Sina döşəmə kafeli – Boz farfor 60×60",
      nameKa: "სინას იატაკის ფილა – ნაცრისფერი ფაიფური 60×60",
      descriptionEn: "Sina floor tile, wear-resistant gray porcelain, suited to hallways and high-traffic spaces.",
      descriptionAz: "Sina döşəmə kafeli, aşınmaya davamlı boz farfor, dəhliz və yüksək hərəkətli məkanlar üçün uyğundur.",
      descriptionKa: "სინას იატაკის ფილა, ცვეთამედეგი ნაცრისფერი ფაიფური, შესაფერისია დერეფნისა და მაღალი დატვირთვის სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "سینا",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 470000,
      unit: "SQUARE_METER",
      stock: 160,
      isFeatured: false,
      isNew: true,
      images: [brandImg("sina-2.jpg"), brandImg("sina-4.jpg")],
    },
    {
      name: "پرسلان سینا مات طرح سیمانی ۸۰×۸۰",
      slug: "sina-matte-cement-porcelain-80x80",
      description: "پرسلان سینا با طرح سیمانی مات، جذب آب پایین، مناسب فضاهای صنعتی و مدرن.",
      nameEn: "Sina Matte Porcelain – Cement 80×80",
      nameAz: "Sina mat farfor – Sement 80×80",
      nameKa: "სინას მქრქალი ფაიფური – ცემენტი 80×80",
      descriptionEn: "Sina porcelain with a matte cement pattern, low water absorption, suited to industrial and modern spaces.",
      descriptionAz: "Sina farfor, mat sement naxışı, aşağı su hopdurma, sənaye və müasir məkanlar üçün uyğundur.",
      descriptionKa: "სინას ფაიფური მქრქალი ცემენტის ნიმუშით, დაბალი წყალშთანთქმა, შესაფერისია სამრეწველო და თანამედროვე სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "سینا",
      size: "80x80",
      color: "طوسی روشن",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 650000,
      unit: "SQUARE_METER",
      stock: 85,
      isFeatured: false,
      isNew: false,
      images: [brandImg("sina-3.jpg"), brandImg("sina-1.jpg")],
    },
    {
      name: "سرامیک سینا طرح چوب روشن ۲۰×۱۲۰",
      slug: "sina-light-wood-ceramic-20x120",
      description: "سرامیک سینا با طرح چوب روشن کشیده، جایگزین اقتصادی و باکیفیت پارکت.",
      nameEn: "Sina Ceramic – Light Wood 20×120",
      nameAz: "Sina keramika – Açıq ağac 20×120",
      nameKa: "სინას კერამიკა – ღია ხის ნიმუში 20×120",
      descriptionEn: "Sina ceramic with an elongated light wood pattern, an economical, high-quality alternative to parquet.",
      descriptionAz: "Sina keramika, uzunsov açıq ağac naxışı, parketə keyfiyyətli və iqtisadi alternativ.",
      descriptionKa: "სინას კერამიკა წაგრძელებული ღია ხის ნიმუშით, პარკეტის ხარისხიანი და ეკონომიური ალტერნატივა.",
      categoryId: ceramic.id,
      brand: "سینا",
      size: "20x120",
      color: "قهوه‌ای روشن",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: false,
      isNew: true,
      images: [brandImg("sina-4.jpg"), brandImg("sina-2.jpg")],
    },

    // --- برند گلدیس ---
    {
      name: "کاشی کف گلدیس طرح آتن طوسی ۶۰×۱۲۰",
      slug: "goldis-athen-gray-60x120",
      description: "کاشی کف گلدیس از کالکشن آتن، طرح طوسی مدرن، مناسب پذیرایی و فضاهای لوکس.",
      nameEn: "Goldis Floor Tile – Athens Gray 60×120",
      nameAz: "Goldis döşəmə kafeli – Athens boz 60×120",
      nameKa: "გოლდისის იატაკის ფილა – Athens ნაცრისფერი 60×120",
      descriptionEn: "Goldis floor tile from the Athens collection, modern gray pattern, suited to living rooms and luxury spaces.",
      descriptionAz: "Goldis döşəmə kafeli, Athens kolleksiyasından, müasir boz naxış, qonaq otağı və lüks məkanlar üçün uyğundur.",
      descriptionKa: "გოლდისის იატაკის ფილა კოლექციიდან Athens, თანამედროვე ნაცრისფერი ნიმუში, შესაფერისია მისაღები ოთახისა და ლუქს სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "گلدیس",
      size: "60x120",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 590000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: true,
      isNew: true,
      images: [brandImg("goldis-1.jpg"), brandImg("goldis-3.jpg")],
    },
    {
      name: "سرامیک گلدیس طرح آراگونیت ۴۰×۴۰",
      slug: "goldis-aragonite-40x40",
      description: "سرامیک گلدیس از کالکشن آراگونیت با طرح سنگ طبیعی، مناسب کف و دیوار.",
      nameEn: "Goldis Ceramic – Aragonite 40×40",
      nameAz: "Goldis keramika – Aragonite 40×40",
      nameKa: "გოლდისის კერამიკა – Aragonite 40×40",
      descriptionEn: "Goldis ceramic from the Aragonite collection with a natural stone pattern, suited to floors and walls.",
      descriptionAz: "Goldis keramika, Aragonite kolleksiyasından, təbii daş naxışı, döşəmə və divar üçün uyğundur.",
      descriptionKa: "გოლდისის კერამიკა კოლექციიდან Aragonite, ბუნებრივი ქვის ნიმუშით, შესაფერისია იატაკისა და კედლისთვის.",
      categoryId: ceramic.id,
      brand: "گلدیس",
      size: "40x40",
      color: "بژ",
      material: "سرامیک",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 340000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("goldis-2.jpg"), brandImg("goldis-1.jpg")],
    },
    {
      name: "پرسلان گلدیس طرح مرمر سفید ۶۰×۱۲۰",
      slug: "goldis-white-marble-porcelain-60x120",
      description: "پرسلان بزرگ‌ابعاد گلدیس با طرح مرمر سفید، مناسب لابی و فضاهای لوکس.",
      nameEn: "Goldis Porcelain – White Marble 60×120",
      nameAz: "Goldis farfor – Ağ mərmər 60×120",
      nameKa: "გოლდისის ფაიფური – თეთრი მარმარილო 60×120",
      descriptionEn: "Large-format Goldis porcelain with a white marble pattern, suited to lobbies and luxury spaces.",
      descriptionAz: "Böyük ölçülü Goldis farfor, ağ mərmər naxışı, lobbi və lüks məkanlar üçün uyğundur.",
      descriptionKa: "მსხვილფორმატიანი გოლდისის ფაიფური თეთრი მარმარილოს ნიმუშით, შესაფერისია ლობისა და ლუქს სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "گلدیس",
      size: "60x120",
      color: "سفید",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 720000,
      unit: "SQUARE_METER",
      stock: 60,
      isFeatured: true,
      isNew: false,
      images: [brandImg("goldis-3.jpg"), brandImg("goldis-4.jpg")],
    },
    {
      name: "کاشی دیوار گلدیس طرح آریس آبی ۶۰×۱۲۰",
      slug: "goldis-aris-blue-60x120",
      description: "کاشی دیوار گلدیس از کالکشن آریس، طرح آبی خاص برای دکوراسیون متفاوت.",
      nameEn: "Goldis Wall Tile – Aris Blue 60×120",
      nameAz: "Goldis divar kafeli – Aris mavi 60×120",
      nameKa: "გოლდისის კედლის ფილა – Aris ლურჯი 60×120",
      descriptionEn: "Goldis wall tile from the Aris collection, a distinctive blue pattern for a different kind of decor.",
      descriptionAz: "Goldis divar kafeli, Aris kolleksiyasından, fərqli dekor üçün xüsusi mavi naxış.",
      descriptionKa: "გოლდისის კედლის ფილა კოლექციიდან Aris, განსხვავებული ლურჯი ნიმუში განსაკუთრებული დეკორისთვის.",
      categoryId: wall.id,
      brand: "گلدیس",
      size: "60x120",
      color: "آبی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 560000,
      unit: "SQUARE_METER",
      stock: 70,
      isFeatured: false,
      isNew: true,
      images: [brandImg("goldis-4.jpg"), brandImg("goldis-3.jpg")],
    },

    // --- برند نوین‌سرام ---
    {
      name: "پرسلان نوین‌سرام طرح هاوانا ۶۰×۱۲۰",
      slug: "novinceram-havana-60x120",
      description: "پرسلان نوین‌سرام از کالکشن هاوانا، طرح مدرن و بزرگ‌ابعاد برای فضاهای امروزی.",
      nameEn: "Novin Ceram Porcelain – Havana 60×120",
      nameAz: "Novin Ceram farfor – Havana 60×120",
      nameKa: "ნოვინ სერამის ფაიფური – Havana 60×120",
      descriptionEn: "Novin Ceram porcelain from the Havana collection, a modern large-format design for contemporary spaces.",
      descriptionAz: "Novin Ceram farfor, Havana kolleksiyasından, müasir məkanlar üçün böyük ölçülü müasir dizayn.",
      descriptionKa: "ნოვინ სერამის ფაიფური კოლექციიდან Havana, თანამედროვე მსხვილფორმატიანი დიზაინი თანამედროვე სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "نوین‌سرام",
      size: "60x120",
      color: "بژ",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 680000,
      unit: "SQUARE_METER",
      stock: 80,
      isFeatured: true,
      isNew: false,
      images: [brandImg("novin-1.jpg"), brandImg("novin-2.jpg")],
    },
    {
      name: "کاشی کف نوین‌سرام مشکی مدرن ۶۰×۶۰",
      slug: "novinceram-black-modern-60x60",
      description: "کاشی کف نوین‌سرام با طرح مشکی مدرن، مناسب فضاهای لوکس و کنتراست بالا.",
      nameEn: "Novin Ceram Floor Tile – Modern Black 60×60",
      nameAz: "Novin Ceram döşəmə kafeli – Müasir qara 60×60",
      nameKa: "ნოვინ სერამის იატაკის ფილა – თანამედროვე შავი 60×60",
      descriptionEn: "Novin Ceram floor tile with a modern black pattern, suited to luxury, high-contrast spaces.",
      descriptionAz: "Novin Ceram döşəmə kafeli, müasir qara naxış, lüks və yüksək kontrastlı məkanlar üçün uyğundur.",
      descriptionKa: "ნოვინ სერამის იატაკის ფილა თანამედროვე შავი ნიმუშით, შესაფერისია ლუქს და მაღალი კონტრასტის სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "نوین‌سرام",
      size: "60x60",
      color: "مشکی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 540000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: false,
      isNew: true,
      images: [brandImg("novin-3.jpg"), brandImg("novin-1.jpg")],
    },
    {
      name: "کاشی دیوار نوین‌سرام طرح روزاریو کرم ۳۰×۹۰",
      slug: "novinceram-rosario-cream-30x90",
      description: "کاشی دیوار نوین‌سرام از کالکشن روزاریو، طرح کرم گرم و شیک.",
      nameEn: "Novin Ceram Wall Tile – Rosario Cream 30×90",
      nameAz: "Novin Ceram divar kafeli – Rosario krem 30×90",
      nameKa: "ნოვინ სერამის კედლის ფილა – Rosario კრემისფერი 30×90",
      descriptionEn: "Novin Ceram wall tile from the Rosario collection, a warm and elegant cream pattern.",
      descriptionAz: "Novin Ceram divar kafeli, Rosario kolleksiyasından, isti və zərif krem naxışı.",
      descriptionKa: "ნოვინ სერამის კედლის ფილა კოლექციიდან Rosario, თბილი და დახვეწილი კრემისფერი ნიმუში.",
      categoryId: wall.id,
      brand: "نوین‌سرام",
      size: "30x90",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 390000,
      unit: "SQUARE_METER",
      stock: 120,
      isFeatured: false,
      isNew: false,
      images: [brandImg("novin-4.jpg"), brandImg("novin-2.jpg")],
    },
    {
      name: "سرامیک نوین‌سرام طرح لاریکس ۲۰×۱۲۰",
      slug: "novinceram-larix-20x120",
      description: "سرامیک نوین‌سرام از کالکشن لاریکس، طرح چوب کشیده برای کف مدرن.",
      nameEn: "Novin Ceram Ceramic – Larix 20×120",
      nameAz: "Novin Ceram keramika – Larix 20×120",
      nameKa: "ნოვინ სერამის კერამიკა – Larix 20×120",
      descriptionEn: "Novin Ceram ceramic from the Larix collection, an elongated wood pattern for modern floors.",
      descriptionAz: "Novin Ceram keramika, Larix kolleksiyasından, müasir döşəmələr üçün uzunsov ağac naxışı.",
      descriptionKa: "ნოვინ სერამის კერამიკა კოლექციიდან Larix, წაგრძელებული ხის ნიმუში თანამედროვე იატაკისთვის.",
      categoryId: ceramic.id,
      brand: "نوین‌سرام",
      size: "20x120",
      color: "قهوه‌ای",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 460000,
      unit: "SQUARE_METER",
      stock: 95,
      isFeatured: false,
      isNew: true,
      images: [brandImg("novin-2.jpg"), brandImg("novin-4.jpg")],
    },

    // --- برند پاسارگاد ---
    {
      name: "کاشی کف پاسارگاد طرح رابل طوسی ۶۰×۶۰",
      slug: "pasargad-rabel-gray-60x60",
      description: "کاشی کف پاسارگاد آباده از کالکشن رابل، طرح طوسی با کیفیت صادراتی.",
      nameEn: "Pasargad Floor Tile – Rabel Gray 60×60",
      nameAz: "Pasarqad döşəmə kafeli – Rabel boz 60×60",
      nameKa: "ფასარგადის იატაკის ფილა – Rabel ნაცრისფერი 60×60",
      descriptionEn: "Pasargad Abadeh floor tile from the Rabel collection, an export-quality gray pattern.",
      descriptionAz: "Pasarqad Abade döşəmə kafeli, Rabel kolleksiyasından, ixrac keyfiyyətli boz naxış.",
      descriptionKa: "ფასარგად აბადეს იატაკის ფილა კოლექციიდან Rabel, საექსპორტო ხარისხის ნაცრისფერი ნიმუში.",
      categoryId: floor.id,
      brand: "پاسارگاد",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 450000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: true,
      isNew: false,
      images: [brandImg("pasargad-1.jpg"), brandImg("pasargad-2.jpg")],
    },
    {
      name: "سرامیک پاسارگاد البرز طوسی ۴۰×۴۰",
      slug: "pasargad-alborz-gray-40x40",
      description: "سرامیک پاسارگاد از کالکشن البرز، طرح طوسی محبوب برای کف و دیوار.",
      nameEn: "Pasargad Ceramic – Alborz Gray 40×40",
      nameAz: "Pasarqad keramika – Alborz boz 40×40",
      nameKa: "ფასარგადის კერამიკა – Alborz ნაცრისფერი 40×40",
      descriptionEn: "Pasargad ceramic from the Alborz collection, a popular gray pattern for floors and walls.",
      descriptionAz: "Pasarqad keramika, Alborz kolleksiyasından, döşəmə və divar üçün məşhur boz naxış.",
      descriptionKa: "ფასარგადის კერამიკა კოლექციიდან Alborz, პოპულარული ნაცრისფერი ნიმუში იატაკისა და კედლისთვის.",
      categoryId: ceramic.id,
      brand: "پاسارگاد",
      size: "40x40",
      color: "طوسی",
      material: "سرامیک",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 280000,
      unit: "SQUARE_METER",
      stock: 170,
      isFeatured: false,
      isNew: false,
      images: [brandImg("pasargad-3.jpg"), brandImg("pasargad-1.jpg")],
    },
    {
      name: "کاشی دیوار پاسارگاد طرح بارسلون ۲۵×۴۰",
      slug: "pasargad-barcelona-25x40",
      description: "کاشی دیوار پاسارگاد از کالکشن بارسلون، طرح شیک و متفاوت برای آشپزخانه.",
      nameEn: "Pasargad Wall Tile – Barcelona 25×40",
      nameAz: "Pasarqad divar kafeli – Barcelona 25×40",
      nameKa: "ფასარგადის კედლის ფილა – Barcelona 25×40",
      descriptionEn: "Pasargad wall tile from the Barcelona collection, an elegant, distinctive pattern for the kitchen.",
      descriptionAz: "Pasarqad divar kafeli, Barcelona kolleksiyasından, mətbəx üçün zərif və fərqli naxış.",
      descriptionKa: "ფასარგადის კედლის ფილა კოლექციიდან Barcelona, დახვეწილი და განსხვავებული ნიმუში სამზარეულოსთვის.",
      categoryId: wall.id,
      brand: "پاسارگاد",
      size: "25x40",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 260000,
      unit: "SQUARE_METER",
      stock: 150,
      isFeatured: false,
      isNew: true,
      images: [brandImg("pasargad-4.jpg"), brandImg("pasargad-2.jpg")],
    },
    {
      name: "پرسلان پاسارگاد صادراتی ۸۰×۸۰",
      slug: "pasargad-export-porcelain-80x80",
      description: "پرسلان پاسارگاد با کیفیت صادراتی به کشورهای حوزه خلیج فارس و اروپا.",
      nameEn: "Pasargad Export Porcelain 80×80",
      nameAz: "Pasarqad ixrac farforu 80×80",
      nameKa: "ფასარგადის საექსპორტო ფაიფური 80×80",
      descriptionEn: "Pasargad export-quality porcelain, shipped to the Persian Gulf region and Europe.",
      descriptionAz: "Pasarqad ixrac keyfiyyətli farfor, İran körfəzi ölkələrinə və Avropaya göndərilir.",
      descriptionKa: "ფასარგადის საექსპორტო ხარისხის ფაიფური, მიეწოდება სპარსეთის ყურის ქვეყნებსა და ევროპას.",
      categoryId: porcelain.id,
      brand: "پاسارگاد",
      size: "80x80",
      color: "کرم",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 610000,
      unit: "SQUARE_METER",
      stock: 65,
      isFeatured: true,
      isNew: false,
      images: [brandImg("pasargad-2.jpg"), brandImg("pasargad-4.jpg")],
    },

    // --- برند تک‌سرام ---
    {
      name: "کاشی کف تک‌سرام طرح مدرن ۶۰×۶۰",
      slug: "takceram-modern-floor-60x60",
      description: "کاشی کف تک‌سرام با طراحی مدرن، مناسب فضاهای مسکونی و تجاری.",
      nameEn: "Tak Ceram Floor Tile – Modern 60×60",
      nameAz: "Tak Ceram döşəmə kafeli – Müasir 60×60",
      nameKa: "თაქ სერამის იატაკის ფილა – თანამედროვე 60×60",
      descriptionEn: "Tak Ceram floor tile with a modern design, suited to residential and commercial spaces.",
      descriptionAz: "Tak Ceram döşəmə kafeli, müasir dizayn, yaşayış və kommersiya məkanları üçün uyğundur.",
      descriptionKa: "თაქ სერამის იატაკის ფილა თანამედროვე დიზაინით, შესაფერისია საცხოვრებელი და კომერციული სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "تک‌سرام",
      size: "60x60",
      color: "طوسی روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 430000,
      unit: "SQUARE_METER",
      stock: 145,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-1.jpg"), brandImg("takceram-2.jpg")],
    },
    {
      name: "کاشی دیوار تک‌سرام سفید براق ۲۵×۴۰",
      slug: "takceram-white-glossy-25x40",
      description: "کاشی دیوار تک‌سرام سفید براق، مناسب آشپزخانه و حمام‌های کوچک.",
      nameEn: "Tak Ceram Wall Tile – Glossy White 25×40",
      nameAz: "Tak Ceram divar kafeli – Parlaq ağ 25×40",
      nameKa: "თაქ სერამის კედლის ფილა – პრიალა თეთრი 25×40",
      descriptionEn: "Tak Ceram glossy white wall tile, suited to kitchens and small bathrooms.",
      descriptionAz: "Tak Ceram parlaq ağ divar kafeli, mətbəx və kiçik hamamlar üçün uyğundur.",
      descriptionKa: "თაქ სერამის პრიალა თეთრი კედლის ფილა, შესაფერისია სამზარეულოსა და პატარა აბაზანისთვის.",
      categoryId: wall.id,
      brand: "تک‌سرام",
      size: "25x40",
      color: "سفید",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 250000,
      unit: "SQUARE_METER",
      stock: 200,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-3.jpg"), brandImg("takceram-1.jpg")],
    },
    {
      name: "سرامیک تک‌سرام طرح چوب ۲۰×۱۲۰",
      slug: "takceram-wood-20x120",
      description: "سرامیک تک‌سرام با طرح چوب طبیعی، مناسب کف اتاق خواب و نشیمن.",
      nameEn: "Tak Ceram Ceramic – Wood 20×120",
      nameAz: "Tak Ceram keramika – Ağac 20×120",
      nameKa: "თაქ სერამის კერამიკა – ხის ნიმუში 20×120",
      descriptionEn: "Tak Ceram ceramic with a natural wood pattern, suited to bedroom and living room floors.",
      descriptionAz: "Tak Ceram keramika, təbii ağac naxışı, yataq otağı və qonaq otağı döşəməsi üçün uyğundur.",
      descriptionKa: "თაქ სერამის კერამიკა ბუნებრივი ხის ნიმუშით, შესაფერისია საძინებლისა და მისაღები ოთახის იატაკისთვის.",
      categoryId: ceramic.id,
      brand: "تک‌سرام",
      size: "20x120",
      color: "قهوه‌ای",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 440000,
      unit: "SQUARE_METER",
      stock: 110,
      isFeatured: true,
      isNew: true,
      images: [brandImg("takceram-4.jpg"), brandImg("takceram-2.jpg")],
    },
    {
      name: "پرسلان تک‌سرام مات طوسی ۶۰×۶۰",
      slug: "takceram-matte-gray-porcelain-60x60",
      description: "پرسلان تک‌سرام مات طوسی، مقاوم و باکیفیت برای فضاهای پرتردد.",
      nameEn: "Tak Ceram Matte Porcelain – Gray 60×60",
      nameAz: "Tak Ceram mat farfor – Boz 60×60",
      nameKa: "თაქ სერამის მქრქალი ფაიფური – ნაცრისფერი 60×60",
      descriptionEn: "Tak Ceram matte gray porcelain, durable and high-quality for high-traffic spaces.",
      descriptionAz: "Tak Ceram mat boz farfor, yüksək hərəkətli məkanlar üçün davamlı və keyfiyyətli.",
      descriptionKa: "თაქ სერამის მქრქალი ნაცრისფერი ფაიფური, გამძლე და ხარისხიანი მაღალი დატვირთვის სივრცეებისთვის.",
      categoryId: porcelain.id,
      brand: "تک‌سرام",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 500000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-2.jpg"), brandImg("takceram-4.jpg")],
    },

    // --- محصولات تکمیلی برندهای قبلی ---
    {
      name: "کاشی دیوار الوند طرح کیارا لوکس ۳۰×۹۰",
      slug: "alvand-kiara-luxury-30x90",
      description: "کاشی دیوار الوند از کالکشن کیارا، طرح لوکس برای دکوراسیون خاص.",
      nameEn: "Alvand Wall Tile – Kiara Lux 30×90",
      nameAz: "Alvand divar kafeli – Kiara Lux 30×90",
      nameKa: "ალვანდის კედლის ფილა – Kiara Lux 30×90",
      descriptionEn: "Alvand wall tile from the Kiara collection, a luxury pattern for distinctive decor.",
      descriptionAz: "Alvand divar kafeli, Kiara kolleksiyasından, fərqli dekor üçün lüks naxış.",
      descriptionKa: "ალვანდის კედლის ფილა კოლექციიდან Kiara, ლუქს ნიმუში განსხვავებული დეკორისთვის.",
      categoryId: wall.id,
      brand: "الوند",
      size: "30x90",
      color: "کرم طلایی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 420000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: true,
      isNew: true,
      images: [brandImg("alvand-4.jpg"), brandImg("alvand-5.jpg")],
    },
    {
      name: "کاشی دیوار تبریز طرح مدرن مشکی ۳۰×۹۰",
      slug: "tabriz-modern-black-30x90",
      description: "کاشی دیوار تبریز با طرح مدرن مشکی، مناسب دکوراسیون کنتراست بالا.",
      nameEn: "Tabriz Wall Tile – Modern Black 30×90",
      nameAz: "Təbriz divar kafeli – Müasir qara 30×90",
      nameKa: "თბრიზის კედლის ფილა – თანამედროვე შავი 30×90",
      descriptionEn: "Tabriz wall tile with a modern black pattern, suited to high-contrast decor.",
      descriptionAz: "Təbriz divar kafeli, müasir qara naxış, yüksək kontrastlı dekor üçün uyğundur.",
      descriptionKa: "თბრიზის კედლის ფილა თანამედროვე შავი ნიმუშით, შესაფერისია მაღალი კონტრასტის დეკორისთვის.",
      categoryId: wall.id,
      brand: "تبریز",
      size: "30x90",
      color: "مشکی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 350000,
      unit: "SQUARE_METER",
      stock: 120,
      isFeatured: false,
      isNew: false,
      images: [brandImg("tabriz-2.jpg"), brandImg("tabriz-3.jpg")],
    },
    {
      name: "کاشی کف مرجان طرح نامیب بژ ۶۰×۶۰",
      slug: "marjan-namib-beige-60x60",
      description: "کاشی کف مرجان از کالکشن نامیب، طرح بژ گرم و طبیعی.",
      nameEn: "Marjan Floor Tile – Namib Beige 60×60",
      nameAz: "Mərcan döşəmə kafeli – Namib bej 60×60",
      nameKa: "მარჯანის იატაკის ფილა – Namib ბეჟი 60×60",
      descriptionEn: "Marjan floor tile from the Namib collection, a warm, natural beige pattern.",
      descriptionAz: "Mərcan döşəmə kafeli, Namib kolleksiyasından, isti, təbii bej naxış.",
      descriptionKa: "მარჯანის იატაკის ფილა კოლექციიდან Namib, თბილი, ბუნებრივი ბეჟი ნიმუში.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "60x60",
      color: "بژ",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 105,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-4.jpg"), brandImg("marjan-5.jpg")],
    },
    {
      name: "کاشی دیوار پرسپولیس طرح آرنا ۲۵×۴۰",
      slug: "persepolis-arena-25x40",
      description: "کاشی دیوار پرسپولیس از کالکشن آرنا، طرح متفاوت برای آشپزخانه مدرن.",
      nameEn: "Persepolis Wall Tile – Arena 25×40",
      nameAz: "Persepolis divar kafeli – Arena 25×40",
      nameKa: "ფერსეპოლისის კედლის ფილა – Arena 25×40",
      descriptionEn: "Persepolis wall tile from the Arena collection, a distinctive pattern for modern kitchens.",
      descriptionAz: "Persepolis divar kafeli, Arena kolleksiyasından, müasir mətbəxlər üçün fərqli naxış.",
      descriptionKa: "ფერსეპოლისის კედლის ფილა კოლექციიდან Arena, განსხვავებული ნიმუში თანამედროვე სამზარეულოებისთვის.",
      categoryId: wall.id,
      brand: "پرسپولیس",
      size: "25x40",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 290000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: false,
      isNew: false,
      images: [brandImg("persepolis-5.jpg"), brandImg("persepolis-4.jpg")],
    },
    {
      name: "کاشی کف نیلو طرح کلاسیک ۲۵×۲۵",
      slug: "nilou-classic-25x25",
      description: "کاشی کف نیلو با طرح کلاسیک، مناسب راهرو و فضاهای سنتی.",
      nameEn: "Nilou Floor Tile – Classic 25×25",
      nameAz: "Nilu döşəmə kafeli – Klassik 25×25",
      nameKa: "ნილუს იატაკის ფილა – კლასიკური 25×25",
      descriptionEn: "Nilou floor tile with a classic pattern, suited to hallways and traditional spaces.",
      descriptionAz: "Nilu döşəmə kafeli, klassik naxış, dəhliz və ənənəvi məkanlar üçün uyğundur.",
      descriptionKa: "ნილუს იატაკის ფილა კლასიკური ნიმუშით, შესაფერისია დერეფნისა და ტრადიციული სივრცეებისთვის.",
      categoryId: floor.id,
      brand: "نیلو",
      size: "25x25",
      color: "سفید",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 270000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-4.jpg"), brandImg("nilou-5.jpg")],
    },
  ];

  for (const p of products) {
    const { images, ...data } = p;
    const product = await prisma.product.upsert({
      where: { slug: p.slug },
      create: data,
      update: data,
    });
    await prisma.productImage.deleteMany({ where: { productId: product.id } });
    await prisma.productImage.createMany({
      data: images.map((url, order) => ({ productId: product.id, url, order })),
    });
  }

  const passwordHash = await bcrypt.hash("password123", 10);

  await prisma.user.upsert({
    where: { email: "admin@parsianceram.example" },
    create: {
      name: "مدیر فروشگاه",
      email: "admin@parsianceram.example",
      password: passwordHash,
      role: "ADMIN",
    },
    update: {},
  });

  const testUsers = [
    { name: "نوید احمدی", email: "navid@example.com", totalPurchase: 2500000, loyaltyPoints: 25, tier: "BRONZE" },
    { name: "سارا محمدی", email: "sara@example.com", totalPurchase: 8500000, loyaltyPoints: 85, tier: "SILVER" },
    { name: "علی رضایی", email: "ali@example.com", totalPurchase: 24000000, loyaltyPoints: 240, tier: "GOLD" },
  ];

  for (const u of testUsers) {
    await prisma.user.upsert({
      where: { email: u.email },
      create: { ...u, password: passwordHash, role: "CUSTOMER" },
      update: u,
    });
  }

  await prisma.discountCode.upsert({
    where: { code: "WELCOME10" },
    create: {
      code: "WELCOME10",
      type: "PERCENT",
      value: 10,
      minOrderAmount: 500000,
      maxUses: 100,
      isActive: true,
    },
    update: {},
  });

  console.log("Seed completed:");
  console.log("- admin login: admin@parsianceram.example / password123");
  console.log("- customer logins: navid@example.com, sara@example.com, ali@example.com / password123");
  console.log("- discount code: WELCOME10 (10% off, min 500,000 toman)");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
