// Seed sample data: categories, products, test users (with loyalty points), a discount code.
// Run with: npx prisma db seed
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Real product photos downloaded from each brand's official catalog/site
// (see scripts/_download-brand-images.mjs for sources); served from /public/uploads/brands.
function brandImg(file) {
  return `/uploads/brands/${file}`;
}

async function main() {
  await prisma.loyaltySettings.upsert({
    where: { id: "default" },
    create: { id: "default" },
    update: {},
  });

  const categories = await Promise.all(
    [
      { name: "کاشی دیوار", slug: "wall-tile", description: "انواع کاشی دیوار برای آشپزخانه، حمام و نما" },
      { name: "کاشی کف", slug: "floor-tile", description: "کاشی مقاوم و ضدلغزش برای کف اماکن مسکونی و تجاری" },
      { name: "سرامیک", slug: "ceramic", description: "سرامیک‌های باکیفیت با طرح‌های متنوع" },
      { name: "پرسلان", slug: "porcelain", description: "پرسلان‌های مقاوم با جذب آب پایین" },
    ].map((c) => prisma.category.upsert({ where: { slug: c.slug }, create: c, update: c }))
  );

  const [wall, floor, ceramic, porcelain] = categories;

  const products = [
    {
      name: "کاشی دیوار الوند طرح مرمر سفید ۳۰×۶۰",
      slug: "wall-tile-white-marble-30x60",
      description: "کاشی دیوار الوند با طرح مرمر سفید، مناسب آشپزخانه و حمام، سطح براق و درخشان.",
      categoryId: wall.id,
      brand: "الوند",
      size: "30x60",
      color: "سفید",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 380000,
      unit: "SQUARE_METER",
      stock: 240,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-1.jpg")],
    },
    {
      name: "کاشی دیوار نیلو طرح چوب بژ ۲۵×۴۰",
      slug: "wall-tile-beige-wood-25x40",
      description: "کاشی دیوار نیلو با طراحی الهام‌گرفته از چوب طبیعی، رنگ بژ گرم، مناسب فضای نشیمن.",
      categoryId: wall.id,
      brand: "نیلو",
      size: "25x40",
      color: "بژ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 295000,
      unit: "SQUARE_METER",
      stock: 180,
      isFeatured: false,
      isNew: true,
      images: [brandImg("nilou-2.jpg")],
    },
    {
      name: "کاشی کف الوند طرح گرانیت طوسی ۶۰×۶۰",
      slug: "floor-tile-gray-granite-60x60",
      description: "کاشی کف الوند با طرح گرانیت طوسی، مقاوم در برابر سایش، مناسب راهرو و پذیرایی.",
      categoryId: floor.id,
      brand: "الوند",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 520000,
      unit: "SQUARE_METER",
      stock: 150,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-2.jpg")],
    },
    {
      name: "کاشی کف مرجان ضدلغزش طرح سنگ تیره ۴۰×۴۰",
      slug: "floor-tile-dark-stone-antislip-40x40",
      description: "کاشی کف مرجان ضدلغزش با طرح سنگ طبیعی تیره، مناسب حیاط، تراس و پارکینگ.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "40x40",
      color: "طوسی تیره",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 410000,
      unit: "SQUARE_METER",
      stock: 200,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-1.jpg")],
    },
    {
      name: "سرامیک نیلو طرح گل سنتی ۲۰×۲۰",
      slug: "ceramic-traditional-flower-20x20",
      description: "سرامیک نیلو با طرح سنتی گل، مناسب دکوراسیون ایرانی و سنتی.",
      categoryId: ceramic.id,
      brand: "نیلو",
      size: "20x20",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 260000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-3.jpg")],
    },
    {
      name: "سرامیک کف پرسپولیس آشپزخانه طرح هگزاگونال",
      slug: "ceramic-hexagon-kitchen-floor",
      description: "سرامیک کف پرسپولیس با طرح شش‌ضلعی مدرن، مناسب آشپزخانه‌های امروزی.",
      categoryId: ceramic.id,
      brand: "پرسپولیس",
      size: "20x23",
      color: "سفید و مشکی",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 340000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: true,
      isNew: true,
      images: [brandImg("persepolis-1.jpg")],
    },
    {
      name: "پرسلان الوند مات طرح سیمانی ۸۰×۸۰",
      slug: "porcelain-matte-cement-80x80",
      description: "پرسلان الوند مات با طرح سیمانی مدرن، جذب آب بسیار پایین، مناسب فضاهای صنعتی و مدرن.",
      categoryId: porcelain.id,
      brand: "الوند",
      size: "80x80",
      color: "خاکستری روشن",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 690000,
      unit: "SQUARE_METER",
      stock: 75,
      isFeatured: true,
      isNew: false,
      images: [brandImg("alvand-3.jpg")],
    },
    {
      name: "پرسلان تبریز براق طرح مرمر طلایی ۶۰×۱۲۰",
      slug: "porcelain-gold-marble-60x120",
      description: "پرسلان بزرگ‌ابعاد تبریز با طرح مرمر طلایی، مناسب لابی و فضاهای لوکس.",
      categoryId: porcelain.id,
      brand: "تبریز",
      size: "60x120",
      color: "کرم طلایی",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 890000,
      unit: "SQUARE_METER",
      stock: 40,
      isFeatured: false,
      isNew: true,
      images: [brandImg("tabriz-1.jpg")],
    },
    // --- برند تبریز ---
    {
      name: "کاشی دیوار تبریز طرح آباژور کرم ۲۵×۴۰",
      slug: "tabriz-wall-cream-abazhur-25x40",
      description: "کاشی دیوار تبریز با طرح آباژور کرم‌رنگ، یکی از پرفروش‌ترین طرح‌های صادراتی به بازار قفقاز.",
      categoryId: wall.id,
      brand: "تبریز",
      size: "25x40",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 310000,
      unit: "SQUARE_METER",
      stock: 160,
      isFeatured: true,
      isNew: false,
      images: [brandImg("tabriz-2.jpg")],
    },
    {
      name: "کاشی کف تبریز پرسلان طوسی ۶۰×۶۰",
      slug: "tabriz-floor-gray-porcelain-60x60",
      description: "کاشی کف تبریز، پرسلان طوسی با دوام بالا، از محصولات صادراتی معتبر این برند.",
      categoryId: floor.id,
      brand: "تبریز",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("tabriz-3.jpg")],
    },
    // --- برند مرجان ---
    {
      name: "سرامیک مرجان بدنه قرمز ضداسید ۲۰×۲۰",
      slug: "marjan-red-body-acid-resistant-20x20",
      description: "سرامیک مرجان با بدنه قرمز لعاب‌دار و مقاوم در برابر اسید، مناسب پارکینگ و فضاهای تجاری.",
      categoryId: ceramic.id,
      brand: "مرجان",
      size: "20x20",
      color: "قرمز",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 230000,
      unit: "SQUARE_METER",
      stock: 220,
      isFeatured: false,
      isNew: false,
      images: [brandImg("marjan-2.jpg")],
    },
    {
      name: "کاشی کف مرجان طرح گرانیت مشکی ۴۰×۴۰",
      slug: "marjan-black-granite-40x40",
      description: "کاشی کف مرجان با طرح گرانیت مشکی، از محصولات پرفروش این برند برای فضاهای مدرن.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "40x40",
      color: "مشکی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 350000,
      unit: "SQUARE_METER",
      stock: 110,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-3.jpg")],
    },
    // --- برند پرسپولیس ---
    {
      name: "کاشی دیوار پرسپولیس طرح گلبرگ فانتزی ۲۵×۴۰",
      slug: "persepolis-flower-fantasy-25x40",
      description: "کاشی دیوار پرسپولیس با طرح فانتزی گلبرگ، مناسب دکوراسیون مدرن آشپزخانه.",
      categoryId: wall.id,
      brand: "پرسپولیس",
      size: "25x40",
      color: "صورتی روشن",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 275000,
      unit: "SQUARE_METER",
      stock: 170,
      isFeatured: false,
      isNew: true,
      images: [brandImg("persepolis-2.jpg")],
    },
    {
      name: "کاشی کف پرسپولیس طرح چوب روشن ۲۰×۱۲۰",
      slug: "persepolis-light-wood-20x120",
      description: "کاشی کف پرسپولیس با طرح چوب روشن کشیده، جایگزین اقتصادی پارکت برای کف منزل.",
      categoryId: floor.id,
      brand: "پرسپولیس",
      size: "20x120",
      color: "قهوه‌ای روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: false,
      price: 520000,
      unit: "SQUARE_METER",
      stock: 95,
      isFeatured: true,
      isNew: false,
      images: [brandImg("persepolis-3.jpg")],
    },
    // --- برند نیلو ---
    {
      name: "کاشی کف نیلو پرسلان روشن ۶۰×۶۰",
      slug: "nilou-light-porcelain-60x60",
      description: "کاشی کف نیلو، پرسلان روشن با کیفیت صادراتی، از پرفروش‌ترین سایزهای این برند.",
      categoryId: floor.id,
      brand: "نیلو",
      size: "60x60",
      color: "بژ روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 510000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-1.jpg")],
    },

    // --- برند سینا ---
    {
      name: "کاشی دیوار سینا طرح مدرن کرم ۲۵×۴۰",
      slug: "sina-wall-cream-modern-25x40",
      description: "کاشی دیوار سینا با طرح مدرن کرم‌رنگ، مناسب آشپزخانه و فضاهای نشیمن امروزی.",
      categoryId: wall.id,
      brand: "سینا",
      size: "25x40",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 300000,
      unit: "SQUARE_METER",
      stock: 190,
      isFeatured: true,
      isNew: false,
      images: [brandImg("sina-1.jpg"), brandImg("sina-3.jpg")],
    },
    {
      name: "کاشی کف سینا پرسلان طوسی ۶۰×۶۰",
      slug: "sina-floor-gray-porcelain-60x60",
      description: "کاشی کف سینا، پرسلان طوسی مقاوم در برابر سایش، مناسب راهرو و فضاهای پرتردد.",
      categoryId: floor.id,
      brand: "سینا",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 470000,
      unit: "SQUARE_METER",
      stock: 160,
      isFeatured: false,
      isNew: true,
      images: [brandImg("sina-2.jpg"), brandImg("sina-4.jpg")],
    },
    {
      name: "پرسلان سینا مات طرح سیمانی ۸۰×۸۰",
      slug: "sina-matte-cement-porcelain-80x80",
      description: "پرسلان سینا با طرح سیمانی مات، جذب آب پایین، مناسب فضاهای صنعتی و مدرن.",
      categoryId: porcelain.id,
      brand: "سینا",
      size: "80x80",
      color: "طوسی روشن",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 650000,
      unit: "SQUARE_METER",
      stock: 85,
      isFeatured: false,
      isNew: false,
      images: [brandImg("sina-3.jpg"), brandImg("sina-1.jpg")],
    },
    {
      name: "سرامیک سینا طرح چوب روشن ۲۰×۱۲۰",
      slug: "sina-light-wood-ceramic-20x120",
      description: "سرامیک سینا با طرح چوب روشن کشیده، جایگزین اقتصادی و باکیفیت پارکت.",
      categoryId: ceramic.id,
      brand: "سینا",
      size: "20x120",
      color: "قهوه‌ای روشن",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: false,
      isNew: true,
      images: [brandImg("sina-4.jpg"), brandImg("sina-2.jpg")],
    },

    // --- برند گلدیس ---
    {
      name: "کاشی کف گلدیس طرح آتن طوسی ۶۰×۱۲۰",
      slug: "goldis-athen-gray-60x120",
      description: "کاشی کف گلدیس از کالکشن آتن، طرح طوسی مدرن، مناسب پذیرایی و فضاهای لوکس.",
      categoryId: floor.id,
      brand: "گلدیس",
      size: "60x120",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 590000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: true,
      isNew: true,
      images: [brandImg("goldis-1.jpg"), brandImg("goldis-3.jpg")],
    },
    {
      name: "سرامیک گلدیس طرح آراگونیت ۴۰×۴۰",
      slug: "goldis-aragonite-40x40",
      description: "سرامیک گلدیس از کالکشن آراگونیت با طرح سنگ طبیعی، مناسب کف و دیوار.",
      categoryId: ceramic.id,
      brand: "گلدیس",
      size: "40x40",
      color: "بژ",
      material: "سرامیک",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 340000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("goldis-2.jpg"), brandImg("goldis-1.jpg")],
    },
    {
      name: "پرسلان گلدیس طرح مرمر سفید ۶۰×۱۲۰",
      slug: "goldis-white-marble-porcelain-60x120",
      description: "پرسلان بزرگ‌ابعاد گلدیس با طرح مرمر سفید، مناسب لابی و فضاهای لوکس.",
      categoryId: porcelain.id,
      brand: "گلدیس",
      size: "60x120",
      color: "سفید",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 720000,
      unit: "SQUARE_METER",
      stock: 60,
      isFeatured: true,
      isNew: false,
      images: [brandImg("goldis-3.jpg"), brandImg("goldis-4.jpg")],
    },
    {
      name: "کاشی دیوار گلدیس طرح آریس آبی ۶۰×۱۲۰",
      slug: "goldis-aris-blue-60x120",
      description: "کاشی دیوار گلدیس از کالکشن آریس، طرح آبی خاص برای دکوراسیون متفاوت.",
      categoryId: wall.id,
      brand: "گلدیس",
      size: "60x120",
      color: "آبی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 560000,
      unit: "SQUARE_METER",
      stock: 70,
      isFeatured: false,
      isNew: true,
      images: [brandImg("goldis-4.jpg"), brandImg("goldis-3.jpg")],
    },

    // --- برند نوین‌سرام ---
    {
      name: "پرسلان نوین‌سرام طرح هاوانا ۶۰×۱۲۰",
      slug: "novinceram-havana-60x120",
      description: "پرسلان نوین‌سرام از کالکشن هاوانا، طرح مدرن و بزرگ‌ابعاد برای فضاهای امروزی.",
      categoryId: porcelain.id,
      brand: "نوین‌سرام",
      size: "60x120",
      color: "بژ",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 680000,
      unit: "SQUARE_METER",
      stock: 80,
      isFeatured: true,
      isNew: false,
      images: [brandImg("novin-1.jpg"), brandImg("novin-2.jpg")],
    },
    {
      name: "کاشی کف نوین‌سرام مشکی مدرن ۶۰×۶۰",
      slug: "novinceram-black-modern-60x60",
      description: "کاشی کف نوین‌سرام با طرح مشکی مدرن، مناسب فضاهای لوکس و کنتراست بالا.",
      categoryId: floor.id,
      brand: "نوین‌سرام",
      size: "60x60",
      color: "مشکی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 540000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: false,
      isNew: true,
      images: [brandImg("novin-3.jpg"), brandImg("novin-1.jpg")],
    },
    {
      name: "کاشی دیوار نوین‌سرام طرح روزاریو کرم ۳۰×۹۰",
      slug: "novinceram-rosario-cream-30x90",
      description: "کاشی دیوار نوین‌سرام از کالکشن روزاریو، طرح کرم گرم و شیک.",
      categoryId: wall.id,
      brand: "نوین‌سرام",
      size: "30x90",
      color: "کرم",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 390000,
      unit: "SQUARE_METER",
      stock: 120,
      isFeatured: false,
      isNew: false,
      images: [brandImg("novin-4.jpg"), brandImg("novin-2.jpg")],
    },
    {
      name: "سرامیک نوین‌سرام طرح لاریکس ۲۰×۱۲۰",
      slug: "novinceram-larix-20x120",
      description: "سرامیک نوین‌سرام از کالکشن لاریکس، طرح چوب کشیده برای کف مدرن.",
      categoryId: ceramic.id,
      brand: "نوین‌سرام",
      size: "20x120",
      color: "قهوه‌ای",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 460000,
      unit: "SQUARE_METER",
      stock: 95,
      isFeatured: false,
      isNew: true,
      images: [brandImg("novin-2.jpg"), brandImg("novin-4.jpg")],
    },

    // --- برند پاسارگاد ---
    {
      name: "کاشی کف پاسارگاد طرح رابل طوسی ۶۰×۶۰",
      slug: "pasargad-rabel-gray-60x60",
      description: "کاشی کف پاسارگاد آباده از کالکشن رابل، طرح طوسی با کیفیت صادراتی.",
      categoryId: floor.id,
      brand: "پاسارگاد",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 450000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: true,
      isNew: false,
      images: [brandImg("pasargad-1.jpg"), brandImg("pasargad-2.jpg")],
    },
    {
      name: "سرامیک پاسارگاد البرز طوسی ۴۰×۴۰",
      slug: "pasargad-alborz-gray-40x40",
      description: "سرامیک پاسارگاد از کالکشن البرز، طرح طوسی محبوب برای کف و دیوار.",
      categoryId: ceramic.id,
      brand: "پاسارگاد",
      size: "40x40",
      color: "طوسی",
      material: "سرامیک",
      usage: "کف و دیوار",
      antiSlip: false,
      price: 280000,
      unit: "SQUARE_METER",
      stock: 170,
      isFeatured: false,
      isNew: false,
      images: [brandImg("pasargad-3.jpg"), brandImg("pasargad-1.jpg")],
    },
    {
      name: "کاشی دیوار پاسارگاد طرح بارسلون ۲۵×۴۰",
      slug: "pasargad-barcelona-25x40",
      description: "کاشی دیوار پاسارگاد از کالکشن بارسلون، طرح شیک و متفاوت برای آشپزخانه.",
      categoryId: wall.id,
      brand: "پاسارگاد",
      size: "25x40",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 260000,
      unit: "SQUARE_METER",
      stock: 150,
      isFeatured: false,
      isNew: true,
      images: [brandImg("pasargad-4.jpg"), brandImg("pasargad-2.jpg")],
    },
    {
      name: "پرسلان پاسارگاد صادراتی ۸۰×۸۰",
      slug: "pasargad-export-porcelain-80x80",
      description: "پرسلان پاسارگاد با کیفیت صادراتی به کشورهای حوزه خلیج فارس و اروپا.",
      categoryId: porcelain.id,
      brand: "پاسارگاد",
      size: "80x80",
      color: "کرم",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 610000,
      unit: "SQUARE_METER",
      stock: 65,
      isFeatured: true,
      isNew: false,
      images: [brandImg("pasargad-2.jpg"), brandImg("pasargad-4.jpg")],
    },

    // --- برند تک‌سرام ---
    {
      name: "کاشی کف تک‌سرام طرح مدرن ۶۰×۶۰",
      slug: "takceram-modern-floor-60x60",
      description: "کاشی کف تک‌سرام با طراحی مدرن، مناسب فضاهای مسکونی و تجاری.",
      categoryId: floor.id,
      brand: "تک‌سرام",
      size: "60x60",
      color: "طوسی روشن",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 430000,
      unit: "SQUARE_METER",
      stock: 145,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-1.jpg"), brandImg("takceram-2.jpg")],
    },
    {
      name: "کاشی دیوار تک‌سرام سفید براق ۲۵×۴۰",
      slug: "takceram-white-glossy-25x40",
      description: "کاشی دیوار تک‌سرام سفید براق، مناسب آشپزخانه و حمام‌های کوچک.",
      categoryId: wall.id,
      brand: "تک‌سرام",
      size: "25x40",
      color: "سفید",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 250000,
      unit: "SQUARE_METER",
      stock: 200,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-3.jpg"), brandImg("takceram-1.jpg")],
    },
    {
      name: "سرامیک تک‌سرام طرح چوب ۲۰×۱۲۰",
      slug: "takceram-wood-20x120",
      description: "سرامیک تک‌سرام با طرح چوب طبیعی، مناسب کف اتاق خواب و نشیمن.",
      categoryId: ceramic.id,
      brand: "تک‌سرام",
      size: "20x120",
      color: "قهوه‌ای",
      material: "سرامیک",
      usage: "کف",
      antiSlip: false,
      price: 440000,
      unit: "SQUARE_METER",
      stock: 110,
      isFeatured: true,
      isNew: true,
      images: [brandImg("takceram-4.jpg"), brandImg("takceram-2.jpg")],
    },
    {
      name: "پرسلان تک‌سرام مات طوسی ۶۰×۶۰",
      slug: "takceram-matte-gray-porcelain-60x60",
      description: "پرسلان تک‌سرام مات طوسی، مقاوم و باکیفیت برای فضاهای پرتردد.",
      categoryId: porcelain.id,
      brand: "تک‌سرام",
      size: "60x60",
      color: "طوسی",
      material: "پرسلان",
      usage: "کف و دیوار",
      antiSlip: true,
      price: 500000,
      unit: "SQUARE_METER",
      stock: 90,
      isFeatured: false,
      isNew: false,
      images: [brandImg("takceram-2.jpg"), brandImg("takceram-4.jpg")],
    },

    // --- محصولات تکمیلی برندهای قبلی ---
    {
      name: "کاشی دیوار الوند طرح کیارا لوکس ۳۰×۹۰",
      slug: "alvand-kiara-luxury-30x90",
      description: "کاشی دیوار الوند از کالکشن کیارا، طرح لوکس برای دکوراسیون خاص.",
      categoryId: wall.id,
      brand: "الوند",
      size: "30x90",
      color: "کرم طلایی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 420000,
      unit: "SQUARE_METER",
      stock: 100,
      isFeatured: true,
      isNew: true,
      images: [brandImg("alvand-4.jpg"), brandImg("alvand-5.jpg")],
    },
    {
      name: "کاشی دیوار تبریز طرح مدرن مشکی ۳۰×۹۰",
      slug: "tabriz-modern-black-30x90",
      description: "کاشی دیوار تبریز با طرح مدرن مشکی، مناسب دکوراسیون کنتراست بالا.",
      categoryId: wall.id,
      brand: "تبریز",
      size: "30x90",
      color: "مشکی",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 350000,
      unit: "SQUARE_METER",
      stock: 120,
      isFeatured: false,
      isNew: false,
      images: [brandImg("tabriz-2.jpg"), brandImg("tabriz-3.jpg")],
    },
    {
      name: "کاشی کف مرجان طرح نامیب بژ ۶۰×۶۰",
      slug: "marjan-namib-beige-60x60",
      description: "کاشی کف مرجان از کالکشن نامیب، طرح بژ گرم و طبیعی.",
      categoryId: floor.id,
      brand: "مرجان",
      size: "60x60",
      color: "بژ",
      material: "پرسلان",
      usage: "کف",
      antiSlip: true,
      price: 480000,
      unit: "SQUARE_METER",
      stock: 105,
      isFeatured: false,
      isNew: true,
      images: [brandImg("marjan-4.jpg"), brandImg("marjan-5.jpg")],
    },
    {
      name: "کاشی دیوار پرسپولیس طرح آرنا ۲۵×۴۰",
      slug: "persepolis-arena-25x40",
      description: "کاشی دیوار پرسپولیس از کالکشن آرنا، طرح متفاوت برای آشپزخانه مدرن.",
      categoryId: wall.id,
      brand: "پرسپولیس",
      size: "25x40",
      color: "چندرنگ",
      material: "سرامیک",
      usage: "دیوار",
      antiSlip: false,
      price: 290000,
      unit: "SQUARE_METER",
      stock: 130,
      isFeatured: false,
      isNew: false,
      images: [brandImg("persepolis-5.jpg"), brandImg("persepolis-4.jpg")],
    },
    {
      name: "کاشی کف نیلو طرح کلاسیک ۲۵×۲۵",
      slug: "nilou-classic-25x25",
      description: "کاشی کف نیلو با طرح کلاسیک، مناسب راهرو و فضاهای سنتی.",
      categoryId: floor.id,
      brand: "نیلو",
      size: "25x25",
      color: "سفید",
      material: "سرامیک",
      usage: "کف",
      antiSlip: true,
      price: 270000,
      unit: "SQUARE_METER",
      stock: 140,
      isFeatured: false,
      isNew: false,
      images: [brandImg("nilou-4.jpg"), brandImg("nilou-5.jpg")],
    },
  ];

  for (const p of products) {
    const { images, ...data } = p;
    const product = await prisma.product.upsert({
      where: { slug: p.slug },
      create: data,
      update: data,
    });
    await prisma.productImage.deleteMany({ where: { productId: product.id } });
    await prisma.productImage.createMany({
      data: images.map((url, order) => ({ productId: product.id, url, order })),
    });
  }

  const passwordHash = await bcrypt.hash("password123", 10);

  await prisma.user.upsert({
    where: { email: "admin@parsianceram.example" },
    create: {
      name: "مدیر فروشگاه",
      email: "admin@parsianceram.example",
      password: passwordHash,
      role: "ADMIN",
    },
    update: {},
  });

  const testUsers = [
    { name: "نوید احمدی", email: "navid@example.com", totalPurchase: 2500000, loyaltyPoints: 25, tier: "BRONZE" },
    { name: "سارا محمدی", email: "sara@example.com", totalPurchase: 8500000, loyaltyPoints: 85, tier: "SILVER" },
    { name: "علی رضایی", email: "ali@example.com", totalPurchase: 24000000, loyaltyPoints: 240, tier: "GOLD" },
  ];

  for (const u of testUsers) {
    await prisma.user.upsert({
      where: { email: u.email },
      create: { ...u, password: passwordHash, role: "CUSTOMER" },
      update: u,
    });
  }

  await prisma.discountCode.upsert({
    where: { code: "WELCOME10" },
    create: {
      code: "WELCOME10",
      type: "PERCENT",
      value: 10,
      minOrderAmount: 500000,
      maxUses: 100,
      isActive: true,
    },
    update: {},
  });

  console.log("Seed completed:");
  console.log("- admin login: admin@parsianceram.example / password123");
  console.log("- customer logins: navid@example.com, sara@example.com, ali@example.com / password123");
  console.log("- discount code: WELCOME10 (10% off, min 500,000 toman)");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
